# Generated by Django 4.1.3 on 2022-12-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
