# Generated by Django 4.1.3 on 2022-12-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.IntegerField(default='avatar.svg', null=True),
        ),
    ]
